use anyhow::{Result, bail};
use rgate_core::{Circuit, Direction, Gate, GateKind, Logic, Module};
use std::fmt::Write;

pub const METADATA_BEGIN: &str = "// RGate document begin";
pub const METADATA_END: &str = "// RGate document end";

/// Export the supported circuit subset as executable Verilog plus lossless layout metadata.
pub fn export(circuit: &Circuit) -> Result<String> {
    export_mode(circuit, false)
}

/// HDL execution export: interactive sources use writable backing registers.
pub fn export_interactive(circuit: &Circuit) -> Result<String> {
    export_mode(circuit, true)
}
fn export_mode(circuit: &Circuit, interactive: bool) -> Result<String> {
    circuit.validate()?;
    let mut output = String::from(
        "// Generated by RGate. Times and gate delays are in nanoseconds.\n`timescale 1ns/1ns\n\n",
    );
    for module in &circuit.modules {
        if let Some(source) = &module.verilog {
            output.push_str(source);
            output.push_str(
                "

",
            );
            continue;
        }
        let ports = module
            .nets
            .iter()
            .filter(|net| net.port.is_some())
            .map(|net| identifier(&net.name))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(output, "module {}({ports});", identifier(&module.name))?;
        for net in &module.nets {
            let width = if net.width == 1 {
                String::new()
            } else {
                format!("[{}:0] ", net.width - 1)
            };
            let direction = match net.port {
                Some(Direction::Input) => "input wire",
                Some(Direction::Output) => "output wire",
                Some(Direction::InOut) => "inout wire",
                None => "wire",
            };
            writeln!(output, "  {direction} {width}{};", identifier(&net.name))?;
        }
        for gate in &module.gates {
            if interactive
                && matches!(
                    gate.kind,
                    GateKind::Switch | GateKind::Dip | GateKind::Peripheral
                )
            {
                if let Some(net) = self::output(module, gate, "Z") {
                    let state = identifier(&format!("__rgate_input_{}", gate.id.0));
                    let bits = gate
                        .initial
                        .resized(gate.width)
                        .bits()
                        .iter()
                        .rev()
                        .map(ToString::to_string)
                        .collect::<String>();
                    writeln!(
                        output,
                        "reg [{}:0] {state} = {}'b{bits}; assign {net} = {state};",
                        gate.width - 1,
                        gate.width
                    )?;
                }
            } else {
                export_gate(&mut output, module, gate)?;
            }
        }
        output.push_str("endmodule\n\n");
    }
    output.push_str(METADATA_BEGIN);
    output.push('\n');
    for line in crate::native::encode(circuit)?.lines() {
        writeln!(output, "// {line}")?;
    }
    output.push_str(METADATA_END);
    output.push('\n');
    Ok(output)
}

pub(crate) fn identifier(name: &str) -> String {
    if !name.is_empty()
        && name.chars().enumerate().all(|(index, ch)| {
            ch == '_'
                || ch.is_ascii_alphabetic()
                || (index > 0 && (ch.is_ascii_digit() || ch == '$'))
        })
    {
        name.into()
    } else {
        format!("\\{name} ")
    }
}

pub(crate) fn signal(module: &Module, gate: &Gate, pin: &str) -> String {
    gate.pin(pin)
        .and_then(|pin| pin.net)
        .and_then(|net| module.net(net))
        .map(|net| identifier(&net.name))
        .unwrap_or_else(|| format!("{}'bz", gate.pin_width(pin)))
}

pub(crate) fn output(module: &Module, gate: &Gate, pin: &str) -> Option<String> {
    gate.pin(pin)
        .and_then(|pin| pin.net)
        .and_then(|net| module.net(net))
        .map(|net| identifier(&net.name))
}

fn export_gate(text: &mut String, module: &Module, gate: &Gate) -> Result<()> {
    let assign = |text: &mut String, pin: &str, expression: String| -> Result<()> {
        if let Some(net) = output(module, gate, pin) {
            writeln!(text, "  assign #{} {net} = {expression};", gate.delay)?;
        }
        Ok(())
    };
    match &gate.kind {
        kind if kind.is_logic() => {
            let op = match kind {
                GateKind::And | GateKind::Nand | GateKind::ReduceAnd | GateKind::ReduceNand => {
                    " & "
                }
                GateKind::Or | GateKind::Nor | GateKind::ReduceOr | GateKind::ReduceNor => " | ",
                _ => " ^ ",
            };
            let operands = gate
                .pins
                .iter()
                .filter(|pin| pin.direction == Direction::Input)
                .map(|pin| {
                    let signal = signal(module, gate, &pin.name);
                    let scalar = pin
                        .net
                        .and_then(|net| module.net(net))
                        .is_some_and(|net| net.width == 1);
                    if scalar
                        && gate.width > 1
                        && !gate.kind.is_reduction()
                        && !gate.config.reduction
                    {
                        format!("{{{}{{{signal}}}}}", gate.width)
                    } else {
                        signal
                    }
                })
                .collect::<Vec<_>>()
                .join(op);
            let inverted = matches!(
                kind,
                GateKind::Nand
                    | GateKind::Nor
                    | GateKind::Xnor
                    | GateKind::ReduceNand
                    | GateKind::ReduceNor
                    | GateKind::ReduceXnor
            );
            let operands = if kind.is_reduction() || gate.config.reduction {
                format!("{}({operands})", op.trim())
            } else {
                operands
            };
            assign(
                text,
                "Z",
                format!("{}({operands})", if inverted { "~" } else { "" }),
            )?;
        }
        GateKind::Buffer | GateKind::TriState => {
            if let Some(net) = output(module, gate, "Z") {
                let primitive = if gate.kind == GateKind::Buffer {
                    "buf"
                } else {
                    match (gate.config.enable_low, gate.config.invert_output) {
                        (false, false) => "bufif1",
                        (true, false) => "bufif0",
                        (false, true) => "notif1",
                        (true, true) => "notif0",
                    }
                };
                let control = if gate.kind == GateKind::TriState {
                    format!(", {}", signal(module, gate, "E"))
                } else {
                    String::new()
                };
                writeln!(
                    text,
                    "  {primitive} #{} {} [{}:0] ({net}, {}{control});",
                    gate.delay,
                    identifier(&format!("__gate_{}", gate.id.0)),
                    gate.width - 1,
                    signal(module, gate, "I")
                )?;
            }
        }
        GateKind::Not => assign(text, "Z", format!("~{}", signal(module, gate, "I")))?,
        GateKind::Ground => assign(text, "Z", format!("{}'b0", gate.width))?,
        GateKind::Vdd => assign(text, "Z", format!("{{{}{{1'b1}}}}", gate.width))?,
        GateKind::Switch | GateKind::Dip => {
            let bits = gate
                .initial
                .resized(gate.width)
                .bits()
                .iter()
                .rev()
                .map(|bit| match bit {
                    Logic::Low => '0',
                    Logic::High => '1',
                    Logic::Unknown => 'x',
                    Logic::HighZ => 'z',
                })
                .collect::<String>();
            assign(text, "Z", format!("{}'b{bits}", gate.width))?;
        }
        GateKind::Clock => {
            if let Some(net) = output(module, gate, "Z") {
                let state = identifier(&format!("{}_state", gate.name));
                writeln!(
                    text,
                    "  reg {state} = 1'b0;\n  initial begin\n    #{};\n    forever begin\n      #{} {state} = 1'b1;\n      #{} {state} = 1'b0;\n    end\n  end\n  assign {net} = {state};",
                    gate.config.clock_phase,
                    gate.clock_low_time(),
                    gate.clock_high_time()
                )?;
            }
        }
        GateKind::Mux => {
            let selection = signal(module, gate, "S");
            let mut expression = format!("{}'bx", gate.width);
            for index in (0..gate.input_count).rev() {
                expression = format!(
                    "({selection} == {index}) ? {} : ({expression})",
                    signal(module, gate, &format!("I{index}"))
                );
            }
            assign(text, "Z", expression)?;
        }
        GateKind::Add => {
            let state = identifier(&format!("{}_sum", gate.name));
            writeln!(text, "  wire [{}:0] {state};", gate.width)?;
            writeln!(
                text,
                "  assign {state} = {{1'b0, {}}} + {{1'b0, {}}} + {};",
                signal(module, gate, "A"),
                signal(module, gate, "B"),
                signal(module, gate, "CI")
            )?;
            assign(text, "S", format!("{state}[{}:0]", gate.width - 1))?;
            assign(text, "CO", format!("{state}[{}]", gate.width))?;
        }
        GateKind::Dff | GateKind::Register => {
            let state = identifier(&format!("{}_state", gate.name));
            let ck = signal(module, gate, "CK");
            let control = |pin: &str, default: &str| {
                if gate.pin(pin).is_none_or(|pin| pin.net.is_none()) {
                    default.into()
                } else {
                    signal(module, gate, pin)
                }
            };
            let clear = control("CLR", "1'b1");
            let enable = control("EN", "1'b0");
            writeln!(text, "  reg [{}:0] {state};", gate.width - 1)?;
            writeln!(
                text,
                "  always @(posedge {ck} or negedge {clear})\n    if (!{clear}) {state} <= {}'b0;\n    else if (!{enable}) {state} <= {};",
                gate.width,
                signal(module, gate, "D")
            )?;
            assign(text, "Q", state.clone())?;
            assign(text, "_Q", format!("~{state}"))?;
        }
        GateKind::Comment | GateKind::Led | GateKind::Frame => {}
        GateKind::Module(name) => {
            let connections = gate
                .pins
                .iter()
                .map(|pin| {
                    let expression = if pin.net.is_some() {
                        signal(module, gate, &pin.name)
                    } else {
                        String::new()
                    };
                    format!(".{}({expression})", identifier(&pin.name))
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                text,
                "  {} {} ({connections});",
                identifier(name),
                identifier(&gate.name)
            )?;
        }
        GateKind::Unsupported(_) => {
            bail!(
                "cannot export unsupported gate {} ({})",
                gate.name,
                gate.kind.name()
            );
        }
        kind if kind.is_extended() => crate::component_verilog::export(text, module, gate)?,
        _ => bail!("cannot export gate {}", gate.name),
    }
    Ok(())
}

pub fn embedded_document(source: &str) -> Result<Option<Circuit>> {
    let Some((_, metadata)) = source.split_once(METADATA_BEGIN) else {
        return Ok(None);
    };
    let Some((metadata, _)) = metadata.split_once(METADATA_END) else {
        bail!("truncated RGate layout metadata");
    };
    let mut json = String::new();
    for line in metadata.lines().filter(|line| !line.trim().is_empty()) {
        let line = line
            .strip_prefix("// ")
            .or_else(|| line.strip_prefix("//"))
            .ok_or_else(|| anyhow::anyhow!("invalid RGate metadata comment"))?;
        json.push_str(line);
        json.push('\n');
    }
    Ok(Some(crate::native::decode(&json)?))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rgate_core::demo;

    #[test]
    fn verilog_round_trip_is_lossless() {
        let circuit = demo::full_adder();
        let source = export(&circuit).unwrap();
        assert!(source.contains("module main("));
        assert!(source.contains(" ^ "));
        assert_eq!(embedded_document(&source).unwrap().unwrap(), circuit);
    }

    #[test]
    fn truncation_is_not_ignored() {
        assert!(embedded_document(METADATA_BEGIN).is_err());
    }
    #[test]
    fn hierarchical_export_writes_named_instances_and_round_trips() {
        let circuit = demo::hierarchical_inverters();
        let source = export(&circuit).unwrap();
        assert!(source.contains("wrapped_inverter u0 (.A(input0), .Y(output0));"));
        assert!(source.contains("inverter inner (.A(A), .Y(Y));"));
        assert_eq!(embedded_document(&source).unwrap().unwrap(), circuit);
    }
    #[test]
    fn reductions_tristate_and_phase_clock_export_correct_constructs() {
        let mut circuit = Circuit::default();
        for (index, kind) in [
            GateKind::ReduceXor,
            GateKind::TriState,
            GateKind::Clock,
            GateKind::Frame,
        ]
        .into_iter()
        .enumerate()
        {
            let mut gate = Gate::new(
                rgate_core::GateId(index as u64 + 1),
                kind,
                rgate_core::Point::ZERO,
            );
            if gate.kind == GateKind::TriState {
                gate.config.enable_low = true;
                gate.config.invert_output = true;
            }
            if gate.kind == GateKind::Clock {
                gate.config.clock_phase = 10;
                gate.config.clock_duty = 25;
            }
            for pin in &mut gate.pins {
                let id = rgate_core::NetId(circuit.modules[0].nets.len() as u64 + 1);
                pin.net = Some(id);
                circuit.modules[0].nets.push(rgate_core::Net::new(
                    id,
                    format!("w{}", id.0),
                    pin.width.unwrap_or(gate.width),
                ));
            }
            circuit.modules[0].gates.push(gate);
        }
        let source = export(&circuit).unwrap();
        assert!(source.contains("^("));
        assert!(source.contains("notif0"));
        assert!(source.contains("#75"));
        assert!(source.contains("#25"));
        assert_eq!(embedded_document(&source).unwrap().unwrap(), circuit);
    }
}
