[package]
name = "rgate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[features]
default = ["icarus"]
icarus = ["rgate-ui/icarus"]

[dependencies]
rgate-ui.workspace = true
rgate-core.workspace = true
rgate-format.workspace = true
rgate-sim.workspace = true
anyhow.workspace = true
